package application.datamembers;

public enum AttrName {
COLLECTION, GENDER, DESCRIPTION, DETAIL_DESC, COLOR, SIZE, NEW_ARRIVAL, BRAND, SEASON, STYLE, OUR_FAVORITE,
NEW_COLLECTION,TREND,NEW_NAME,LUX,EXCLUSIVE
}
